### ISSUE TITLE
how to send input request to the loaded bert_pt model 

### ISSUE THREAD

**Issue by rkoystart** [NVIDIA/triton-inference-server#1390]
[model_repository](https://github.com/rkoystart/trtiton-inference-server/tree/master/model_repository/bert_pt ) In this link i have the model repository to upload the bert_pt model . I have successfully started the inference server . 
checked the model status by calling  **curl localhost:8000/api/status** and it says **model ready**
Before starting the server i have executed the program [bert model for creating the model.pt](https://github.com/rkoystart/trtiton-inference-server/blob/master/bert_pt.py) so that te model.pt is saved in **1/** 
Now i have downloaded this **image nvcr.io/nvidia/tensorrtserver:20.02-py3-clientsdk** and executed the command 
`sudo docker run -it --rm --net=host nvcr.io/nvidia/tritonserver:20.02-py3-clientsdk `
Now i am inside the client container , and executed the command 

`perf_client -m bert_pt --input-data "zero"` 

and the output was 
```
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
Failed to update context stat: [ 0] INTERNAL - Timer not set correctly.
[ 0] INTERNAL - Failed to maintain requested inference load. Worker thread(s) failed to generate concurrent requests.
Thread [0] had error: [inference:0 21] INTERNAL - failed to run model 'bert_pt_0_gpu1

```
and I logged the error trace 
```
I0504 10:13:31.692356 1 libtorch_backend.cc:805] arguments are located on different GPUs at /tmp/pip-req-build-xngg3b67/aten/src/THC/generic/THCTensorIndex.cu:398                                          
The above operation failed in interpreter.                                                                                                                                                                  
Traceback (most recent call last):                                                                                                                                                                          
Serialized   File "code/__torch__.py", line 9                                                                                                                                                               
    _0 = self.model                                                                                                                                                                                         
    input_ids = torch.to(data, dtype=4, layout=0, device=torch.device("cuda"), pin_memory=False, non_blocking=False, copy=False, memory_format=None)                                                        
    _1 = torch.select((_0).forward(input_ids, ), 0, 0)                                                                                                                                                      
                       ~~~~~~~~~~~ <--- HERE                                                                                                                                                                
    return _1                                                                                                                                                                                               
Serialized   File "code/__torch__/transformers/modeling_bert.py", line 10, in forward                                                                                                                       
    input_ids: Tensor) -> Tensor:
    _0 = self.classifier
    _1 = (self.dropout).forward((self.bert).forward(input_ids, ), )
                                 ~~~~~~~~~~~~~~~~~~ <--- HERE
    return (_0).forward(_1, )
class BertModel(Module):
Serialized   File "code/__torch__/transformers/modeling_bert.py", line 35, in forward
    _12 = torch.to(extended_attention_mask, 6, False, False, None)
    attention_mask0 = torch.mul(torch.rsub(_12, 1., 1), CONSTANTS.c0)
    _13 = (_3).forward((_4).forward(input_ids, input, ), attention_mask0, )
                        ~~~~~~~~~~~ <--- HERE
    return (_2).forward(_13, )
class BertEmbeddings(Module):
Serialized   File "code/__torch__/transformers/modeling_bert.py", line 59, in forward
    position_ids = torch.arange(annotate(number, seq_length), dtype=4, layout=0, device=torch.device("cuda:0"), pin_memory=False)
    input0 = torch.expand(torch.unsqueeze(position_ids, 0), [_20, _21], implicit=False)
    _22 = (_18).forward(input_ids, )
           ~~~~~~~~~~~~ <--- HERE
    _23 = (_17).forward(input0, )
    _24 = (_16).forward(input, )
/home/rk/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py(1724): embedding
/home/rk/anaconda3/lib/python3.7/site-packages/torch/nn/modules/sparse.py(114): forward
/home/rk/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py(534): _slow_forward
/home/rk/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py(548): __call__
/home/rk/anaconda3/lib/python3.7/site-packages/transformers/modeling_bert.py(173): forward
/home/rk/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py(534): _slow_forward
/home/rk/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py(548): __call__
/home/rk/anaconda3/lib/python3.7/site-packages/transformers/modeling_bert.py(783): forward
/home/rk/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py(534): _slow_forward
/home/rk/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py(548): __call__
/home/rk/anaconda3/lib/python3.7/site-packages/transformers/modeling_bert.py(1176): forward
/home/rk/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py(534): _slow_forward
/home/rk/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py(548): __call__
bert_pt.py(12): forward
/home/rk/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py(534): _slow_forward
/home/rk/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py(548): __call__
/home/rk/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py(1027): trace_module
/home/rk/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py(875): trace
bert_pt.py(17): <module>
Serialized   File "code/__torch__/torch/nn/modules/sparse.py", line 7, in forward
  def forward(self: __torch__.torch.nn.modules.sparse.Embedding,
    input_ids: Tensor) -> Tensor:
    inputs_embeds = torch.embedding(self.weight, input_ids, 0, False, False)
                    ~~~~~~~~~~~~~~~ <--- HERE
    return inputs_embeds

I0504 10:13:31.692384 1 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x7f6e1a000090
I0504 10:13:31.692435 1 trtserver.cc:1813] Infer failed: failed to run model 'bert_pt_0_gpu2
```

 all i want to know is how to make valid request to the model **bert_pt**  and I am working in a machine that has 4 gpus
pls let me know !!!!

**Comment by CoderHam** [comment]
Can you confirm that the model runs fine in the case of a single GPU? It would be helpful if you could also share the model with me so I can reproduce and get to the bottom of this issue

**Comment by rkoystart** [comment]
@CoderHam  It is running properly in case of single gpu. The above mentioned error comes when I run it on multiple gpus. 
> [model_repository](https://github.com/rkoystart/trtiton-inference-server/tree/master/model_repository/bert_pt) In this link i have the model repository to upload the bert_pt model . I have successfully started the inference server
> Before starting the server i have executed the program [bert model for creating the model.pt](https://github.com/rkoystart/trtiton-inference-server/blob/master/bert_pt.py) so that te model.pt is saved in **1/**

I have already provided all the code in the above comment . please refer to it regarding the config.pbtxt and the  .py file for creating the model.pt using torchscript

**Comment by CoderHam** [comment]
There are some known bugs in libtorch while running on multiple gpus. The client counts the number of requests that were successfully run by the server. The server counts the total number of requests it received and run successfully (even if they took longer that the latency threshold of the client.

**Comment by CoderHam** [comment]
I tried to access your model_repository but the model appears to be empty in your repo.
`0 lines (0 sloc)  0 Bytes`
Can you fix that? 
Which version of pytorch did you use to produce/trace the model?

**Comment by CoderHam** [comment]
Re-open ticket if the issue persists. Closing now due to inactivity.
