### ISSUE TITLE
GRPC client failed / HTTP client failed

### ISSUE THREAD

**Issue by kylemcdonald** [NVIDIA/triton-inference-server#1543]
**Description**

When I call `ctx.run` to do inference on my model, I get an `InferenceServerException` with the text `InferenceServerException: [ 0] HTTP client failed: Server returned nothing (no headers, no data)` or `InferenceServerException: [ 0] GRPC client failed: 14: Connection reset by peer`, and the server exits with no additional information.

**Triton Information**

NVIDIA Release 20.03 (build 11042949)

Using the Triton container.

**To Reproduce**

I started with an ONNX model for GPT-2. I have confirmed that it runs correctly with the following code:

```python
import onnxruntime as ort
import numpy as np
tokens = [1870,644,318,1842,30,632,318,257,3654,12049,510,13,1114,4686,48795,
    284,269,793,316,11,15849,11,290,288,392,293,26,317,1517,286,2705,2984,77,
    21499,11,523,11871]
input_ids = np.asarray(tokens, dtype=np.int64)
onnx_options = ort.SessionOptions()
onnx_f = ort.InferenceSession('onnx/gpt2-large.onnx', onnx_options, providers=['CUDAExecutionProvider'])
output = onnx_f.run(['word_probs'], { 'input_ids': input_ids[None,:] })[0]
```

I created a `config.pbtxt` for this model as follows:

```
name: "gpt2-large"
platform: "onnxruntime_onnx"
default_model_filename: "gpt2-large.onnx"
max_batch_size: 1
input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [ -1 ]
  }
]
output [
  {
    name: "word_probs"
    data_type: TYPE_INT64
    dims: [ 1 ]
  }
]
version_policy: { all { }}
```

Then I ran triton server, which successfully loads the model:

```
docker run \
  --gpus device=0 \
  --rm \
  --shm-size=1g \
  --ulimit memlock=-1 \
  --ulimit stack=67108864 \
  -p8000:8000 -p8001:8001 -p8002:8002 \
  -v/triton-repository:/models nvcr.io/nvidia/tritonserver:20.03-py3 trtserver \
    --model-repository=/models \
    --log-verbose=1 \
    --log-info=1 \
    --log-warning=1 \
    --log-error=1
```

Here is the output after running:

```
=============================
== Triton Inference Server ==
=============================

NVIDIA Release 20.03 (build 11042949)

Copyright (c) 2018-2019, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying
project or file.

2020-05-23 04:01:24.612876: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
I0523 04:01:24.648712 1 metrics.cc:164] found 1 GPUs supporting NVML metrics
I0523 04:01:24.654233 1 metrics.cc:173]   GPU 0: TITAN RTX
I0523 04:01:24.654491 1 server.cc:120] Initializing Triton Inference Server
I0523 04:01:24.909014 1 pinned_memory_manager.cc:197] Pinned memory pool is created at '0x7fe80a000000' with size 268435456
I0523 04:01:24.909397 1 graphdef_backend_factory.cc:48] Create GraphDefBackendFactory
I0523 04:01:24.909410 1 savedmodel_backend_factory.cc:48] Create SavedModelBackendFactory
I0523 04:01:24.909419 1 netdef_backend_factory.cc:46] Create NetDefBackendFactory
I0523 04:01:24.909427 1 plan_backend_factory.cc:48] Create PlanBackendFactory
I0523 04:01:24.909431 1 plan_backend_factory.cc:55] Registering TensorRT Plugins
I0523 04:01:24.909465 1 logging.cc:52] Plugin creator registration succeeded - ::GridAnchor_TRT
I0523 04:01:24.909480 1 logging.cc:52] Plugin creator registration succeeded - ::NMS_TRT
I0523 04:01:24.909493 1 logging.cc:52] Plugin creator registration succeeded - ::Reorg_TRT
I0523 04:01:24.909500 1 logging.cc:52] Plugin creator registration succeeded - ::Region_TRT
I0523 04:01:24.909506 1 logging.cc:52] Plugin creator registration succeeded - ::Clip_TRT
I0523 04:01:24.909512 1 logging.cc:52] Plugin creator registration succeeded - ::LReLU_TRT
I0523 04:01:24.909519 1 logging.cc:52] Plugin creator registration succeeded - ::PriorBox_TRT
I0523 04:01:24.909525 1 logging.cc:52] Plugin creator registration succeeded - ::Normalize_TRT
I0523 04:01:24.909536 1 logging.cc:52] Plugin creator registration succeeded - ::RPROI_TRT
I0523 04:01:24.909543 1 logging.cc:52] Plugin creator registration succeeded - ::BatchedNMS_TRT
I0523 04:01:24.909549 1 logging.cc:52] Plugin creator registration succeeded - ::FlattenConcat_TRT
I0523 04:01:24.909555 1 logging.cc:52] Plugin creator registration succeeded - ::CropAndResize
I0523 04:01:24.909562 1 logging.cc:52] Plugin creator registration succeeded - ::DetectionLayer_TRT
I0523 04:01:24.909569 1 logging.cc:52] Plugin creator registration succeeded - ::Proposal
I0523 04:01:24.909575 1 logging.cc:52] Plugin creator registration succeeded - ::ProposalLayer_TRT
I0523 04:01:24.909582 1 logging.cc:52] Plugin creator registration succeeded - ::PyramidROIAlign_TRT
I0523 04:01:24.909588 1 logging.cc:52] Plugin creator registration succeeded - ::ResizeNearest_TRT
I0523 04:01:24.909593 1 logging.cc:52] Plugin creator registration succeeded - ::Split
I0523 04:01:24.909599 1 logging.cc:52] Plugin creator registration succeeded - ::SpecialSlice_TRT
I0523 04:01:24.909605 1 logging.cc:52] Plugin creator registration succeeded - ::InstanceNormalization_TRT
I0523 04:01:24.909615 1 onnx_backend_factory.cc:53] Create OnnxBackendFactory
I0523 04:01:24.914255 1 libtorch_backend_factory.cc:46] Create LibTorchBackendFactory
I0523 04:01:24.914272 1 custom_backend_factory.cc:46] Create CustomBackendFactory
I0523 04:01:24.914276 1 ensemble_backend_factory.cc:47] Create EnsembleBackendFactory
I0523 04:01:24.915602 1 server_status.cc:55] New status tracking for model 'gpt2-large'
I0523 04:01:24.915653 1 model_repository_manager.cc:568] AsyncLoad() 'gpt2-large'
I0523 04:01:24.915671 1 model_repository_manager.cc:622] TriggerNextAction() 'gpt2-large' version 1: 1
I0523 04:01:24.915683 1 model_repository_manager.cc:660] Load() 'gpt2-large' version 1
I0523 04:01:24.915687 1 model_repository_manager.cc:680] loading: gpt2-large:1
I0523 04:01:24.915787 1 model_repository_manager.cc:735] CreateInferenceBackend() 'gpt2-large' version 1
I0523 04:01:26.818035 1 onnx_backend.cc:203] Creating instance gpt2-large_0_gpu0 on GPU 0 (7.5) using gpt2-large.onnx
I0523 04:01:26.818092 1 onnx_backend.cc:258] CUDA Execution Accelerator is set for gpt2-large_0_gpu0 on device 0
I0523 04:01:31.100188 1 dynamic_batch_scheduler.cc:233] Starting dynamic-batch scheduler thread 0 at nice 5...
I0523 04:01:31.100257 1 onnx_backend.cc:107] onnx backend for gpt2-large
name=gpt2-large
contexts:
  name=gpt2-large_0_gpu0, gpu=0, max_batch_size=1

I0523 04:01:31.231554 1 model_repository_manager.cc:837] successfully loaded 'gpt2-large' version 1
I0523 04:01:31.231583 1 model_repository_manager.cc:622] TriggerNextAction() 'gpt2-large' version 1: 0
I0523 04:01:31.231590 1 model_repository_manager.cc:637] no next action, trigger OnComplete()
I0523 04:01:31.231736 1 model_repository_manager.cc:492] GetVersionStates() 'gpt2-large'
Starting endpoints, 'inference:0' listening on
I0523 04:01:31.232797 1 grpc_server.cc:494] New request handler for HealthHandler, 1
I0523 04:01:31.232845 1 grpc_server.cc:447] Threads started for HealthHandler
I0523 04:01:31.232946 1 grpc_server.cc:584] New request handler for StatusHandler, 2
I0523 04:01:31.232985 1 grpc_server.cc:447] Threads started for StatusHandler
I0523 04:01:31.233446 1 grpc_server.cc:683] New request handler for RepositoryHandler, 3
I0523 04:01:31.233482 1 grpc_server.cc:447] Threads started for RepositoryHandler
I0523 04:01:31.233564 1 grpc_server.cc:1005] New request handler for InferHandler, 4
I0523 04:01:31.233601 1 grpc_server.cc:447] Threads started for InferHandler
I0523 04:01:31.235238 1 grpc_server.cc:1281] New request handler for StreamInferHandler, 6
I0523 04:01:31.235298 1 grpc_server.cc:447] Threads started for StreamInferHandler
I0523 04:01:31.235504 1 grpc_server.cc:1611] New request handler for ModelControlHandler, 7
I0523 04:01:31.235533 1 grpc_server.cc:447] Threads started for ModelControlHandler
I0523 04:01:31.235733 1 grpc_server.cc:1702] New request handler for SharedMemoryControlHandler, 8
I0523 04:01:31.235780 1 grpc_server.cc:447] Threads started for SharedMemoryControlHandler
I0523 04:01:31.235802 1 grpc_server.cc:1939] Started GRPCService at 0.0.0.0:8001
I0523 04:01:31.235824 1 http_server.cc:1411] Starting HTTPService at 0.0.0.0:8000
I0523 04:01:31.277966 1 http_server.cc:1426] Starting Metrics Service at 0.0.0.0:8002
```

Then when I run the following Python code:

```python
from tensorrtserver.api import ProtocolType, InferContext
import numpy as np

tokens = [1870,644,318,1842,30,632,318,257,3654,12049,510,13,1114,4686,48795,
    284,269,793,316,11,15849,11,290,288,392,293,26,317,1517,286,2705,2984,77,
    21499,11,523,11871]
input_ids = np.asarray(tokens, dtype=np.int64)

protocol = 'http'
model_name = 'gpt2-large'
model_version = None
batch_size = 1
verbose = True
url = '0.0.0.0:8000'
protocol = ProtocolType.from_str(protocol)
ctx = InferContext(url, protocol, model_name, model_version, verbose)
result = ctx.run({ 'input_ids' : (input_ids,) },
                 { 'word_probs' : InferContext.ResultFormat.RAW },
                 batch_size)
```

I get the `InferenceServerException` and the server shuts down. This happens whether I use the `http` protocol and port 8000, or `grpc` and port 8001.

I can see that the request makes it to the server, and it does not print any error, it only exits:

```
I0523 04:12:06.265410 1 http_server.cc:456] HTTP request: 0 /api/status/gpt2-large
I0523 04:12:06.267549 1 http_server.cc:456] HTTP request: 2 /api/infer/gpt2-large
I0523 04:12:06.268012 1 model_repository_manager.cc:511] GetInferenceBackend() 'gpt2-large' version -1
I0523 04:12:06.268149 1 onnx_backend.cc:552] Running gpt2-large_0_gpu0 with 1 request payloads
I0523 04:12:06.268205 1 pinned_memory_manager.cc:131] pinned memory allocation: size 296, addr 0x7fe80a000090
```

I can also see the server is running correctly when I make a request:

```
$ curl localhost:8000/api/status
id: "inference:0"
version: "1.12.0"
uptime_ns: 95551346569
model_status {
  key: "gpt2-large"
  value {
    config {
      name: "gpt2-large"
      platform: "onnxruntime_onnx"
      version_policy {
        all {
        }
      }
      max_batch_size: 1
      input {
        name: "input_ids"
        data_type: TYPE_INT64
        dims: -1
      }
      output {
        name: "word_probs"
        data_type: TYPE_INT64
        dims: 1
      }
      instance_group {
        name: "gpt2-large"
        count: 1
        gpus: 0
        kind: KIND_GPU
      }
      default_model_filename: "gpt2-large.onnx"
      optimization {
        input_pinned_memory {
          enable: true
        }
        output_pinned_memory {
          enable: true
        }
      }
    }
    version_status {
      key: 1
      value {
        ready_state: MODEL_READY
        ready_state_reason {
        }
      }
    }
  }
}
```

**Expected behavior**

I expected to receive a response from the model that is the same as running the short Python script included above.

**Comment by GuanLuo** [comment]
Did the server exit due to a segfault? If so, can you build the server with debug setting to see where the segfault happens?

**Comment by deadeyegoodwin** [comment]
Can you point us to the model so that we can attempt to reproduce.

**Comment by kylemcdonald** [comment]
@GuanLuo I do not see a segfault.

@deadeyegoodwin you can download the model here https://drive.google.com/file/d/1DV0fh7nT01QmATgQQIe62-oLo4paM-Q6/view?usp=sharing

I also included some files for testing the onnx model, starting the Triton server, and testing the Triton server.

```python
import onnxruntime as ort
import numpy as np

tokens = [1870,644,318,1842,30,632,318,257]
input_ids = np.asarray(tokens, dtype=np.int64)
input_ids = input_ids[None,:] # add a batch axis

onnx_options = ort.SessionOptions()
onnx_f = ort.InferenceSession('1/gpt2.onnx', onnx_options, providers=['CUDAExecutionProvider'])
output = onnx_f.run(['word_probs'], { 'input_ids': input_ids })
print(output)
```

```bash
docker run \
  --gpus all \
  --rm \
  --shm-size=1g \
  --ulimit memlock=-1 \
  --ulimit stack=67108864 \
  -p8000:8000 -p8001:8001 -p8002:8002 \
  -v$(pwd)/../:/models nvcr.io/nvidia/tritonserver:20.03-py3 trtserver \
    --model-repository=/models \
    --log-verbose=1 \
    --log-info=1 \
    --log-warning=1 \
    --log-error=1
```

```python
from tensorrtserver.api import ProtocolType, InferContext
import numpy as np

tokens = [1870,644,318,1842,30,632,318,257]
input_ids = np.asarray(tokens, dtype=np.int64)
input_ids = input_ids[None,:] # add a batch axis

protocol = 'http'
model_name = 'gpt2'
model_version = None
batch_size = 1
verbose = True
url = '0.0.0.0:8000'
protocol = ProtocolType.from_str(protocol)
ctx = InferContext(url, protocol, model_name, model_version, verbose)
result = ctx.run({ 'input_ids' : (input_ids,) },
                 { 'word_probs' : InferContext.ResultFormat.RAW },
                 batch_size)
```

**Comment by kylemcdonald** [comment]
The permissions for the file were wrong, but it should now be possible for anyone to download the zip file.

**Comment by deadeyegoodwin** [comment]
The server is segfaulting inside ONNX Runtime. What version of onnx runtime are you using when you run it directly? 20.03 uses ORT 1.1.1. I also tried 20.03.1 which uses ORT 1.2.0 but that fails because you model apparently has some operation that is incorrect for ORT 1.2.0

```
#0  0x00007f77bb615fe1 in onnxruntime::cuda::TernaryElementwisePreparation::TernaryElementwiseBroadcastPrepareHelper(onnxruntime::TensorShape const&, onnxruntime::TensorShape const&, onnxruntime::TensorShape const&, onnxruntime::TensorShape const&) ()
   from /opt/tensorrtserver/bin/../lib/onnx/libonnxruntime.so.1.1.1
#1  0x00007f77bb618ff4 in onnxruntime::cuda::Where<float>::ComputeInternal(onnxruntime::OpKernelContext*) const () from /opt/tensorrtserver/bin/../lib/onnx/libonnxruntime.so.1.1.1
#2  0x00007f77bb4f2274 in onnxruntime::cuda::CudaKernel::Compute(onnxruntime::OpKernelContext*) const () from /opt/tensorrtserver/bin/../lib/onnx/libonnxruntime.so.1.1.1
#3  0x00007f77bbcbc37e in onnxruntime::SequentialExecutor::Execute(onnxruntime::SessionState const&, std::vector<int, std::allocator<int> > const&, std::vector<OrtValue, std::allocator<OrtValue> > const&, std::vector<int, std::allocator<int> > const&, std::vector<OrtValue, std::allocator<OrtValue> >&, std::unordered_map<unsigned long, std::function<onnxruntime::common::Status (onnxruntime::TensorShape const&, OrtMemoryInfo const&, OrtValue&, bool&)>, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, std::function<onnxruntime::common::Status (onnxruntime::TensorShape const&, OrtMemoryInfo const&, OrtValue&, bool&)> > > > const&, onnxruntime::logging::Logger const&) () from /opt/tensorrtserver/bin/../lib/onnx/libonnxruntime.so.1.1.1
#4  0x00007f77bbca874b in onnxruntime::utils::ExecuteGraphImpl(onnxruntime::SessionState const&, onnxruntime::FeedsFetchesManager const&, std::vector<OrtValue, std::allocator<OrtValue> > const&, std::vector<OrtValue, std::allocator<OrtValue> >&, std::unordered_map<unsigned long, std::function<onnxruntime::common::Status (onnxruntime::TensorShape const&, OrtMemoryInfo const&, OrtValue&, bool&)>, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, std::function<onnxruntime::common::Status (onnxruntime::TensorShape const&, OrtMemoryInfo const&, OrtValue&, bool&)> > > > const&, ExecutionMode, bool const&, onnxruntime::logging::Logger const&) ()
   from /opt/tensorrtserver/bin/../lib/onnx/libonnxruntime.so.1.1.1
#5  0x00007f77bbcaa366 in onnxruntime::utils::ExecuteGraph(onnxruntime::SessionState const&, onnxruntime::FeedsFetchesManager&, std::vector<OrtValue, std::allocator<OrtValue> > const&, std::vector<OrtValue, std::allocator<OrtValue> >&, ExecutionMode, bool const&, onnxruntime::logging::Logger const&) () from /opt/tensorrtserver/bin/../lib/onnx/libonnxruntime.so.1.1.1
...
```

**Comment by kylemcdonald** [comment]
@deadeyegoodwin here are the versions I am currently using for my Python environment:

```
onnx              1.7.0
onnxruntime-gpu   1.3.0
onnxruntime-tools 1.3.0.1007
tritongrpcclient  1.12.0
```

**Comment by deadeyegoodwin** [comment]
For 20.03.1 you need to use ONNXRT 1.2.0 and with that you should use ONNX 1.6.0. The ONNXRT version used by triton is listed in the release notes: https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel_20-03-1.html#rel_20-03-1

And I believe for that version of ONNXRT you should use ONNX 1.6. We will include this version information in the support matrix  (reachable from github README and release notes) in future releases.

**Comment by kylemcdonald** [comment]
Thanks. For our application I will need the latest ONNX and ONNXRT, so it looks like Triton will not be an appropriate solution for our case. Closing this issue.

**Comment by deadeyegoodwin** [comment]
Triton updates ONNXRT regularly. The upcoming 20.06 release uses ONRT 1.3.0, which I believe support ONNX 1.7. If you needed to use more recent ONNXRT builds (e.g. nightly) you would need to build your own triton containers using those builds.

**Comment by kylemcdonald** [comment]
@deadeyegoodwin thanks for your help! if i do get it working i will share details here.
