### ISSUE TITLE
tensorrtserver.api.InferenceServerException: [inference:0 49] unexpected shape for output 'features', model configuration shape is [1,128], inference shape is [1,128]

### ISSUE THREAD

**Issue by bobtattvamasi** [NVIDIA/triton-inference-server#1545]
**Description**
I try to inference deepsort model in tensorflow env by triton server and client. 
my config file:
```
name: "DeepSort_tensorflow"
platform: "tensorflow_graphdef"
max_batch_size: 1
input [
  {
    name: "images"
    data_type: TYPE_UINT8
    format: FORMAT_NHWC
    dims: [ 128,64,3 ]
  }
]
output [
  {
    name: "features"
    data_type: TYPE_FP32
    dims: [ 1,1,128 ]
  }
]

```
my code in client:
```
import numpy as np
import os
from builtins import range
from PIL import Image
from tensorrtserver.api import *
import tensorrtserver.api.model_config_pb2 as model_config

from utils import *

from threading import Thread
import cv2
import time

class TRTIS_deepsort(Thread):
    def __init__(self, cap):
        super(TRTIS_deepsort, self).__init__()

        self.protocol = ProtocolType.from_str("HTTP")
        self.url = 'localhost:8000'
        self.model_name = 'DeepSort_tensorflow'
        self.batch_size = 1
        self.verbose = False
        self.model_version = None

        # The correlation ID for the inference. If not specified (or if specified as 0), the inference will have no correlation ID
        self.correlation_id = 0
        # Is use streaming inference API
        # It is only available with gRPC protocol
        self.streaming = False
        self.scalling = 'NONE'
        self.async_set = False

        self.input_name, self.output_name, self.c, self.h, self.w, self.format, self.dtype = parse_model(self.url,
                                                            self.protocol,
                                                            self.model_name,
                                                            self.batch_size,
                                                            self.verbose)
        self.ctx = InferContext(self.url, self.protocol, self.model_name,
                       self.model_version, self.verbose, self.correlation_id, self.streaming)
        self.cap = cap
        _, self.frame = self.cap.read()

    def run(self):

        while (self.cap.isOpened()):
            print('run tf_deepsort_module')
            _, self.frame = self.cap.read()
            if _:
                results = []
                sent_count=0
                pil_image=Image.fromarray(
                          cv2.cvtColor(self.frame, cv2.COLOR_BGR2RGB)
                        )

                image_data = preprocess(pil_image, self.format, self.dtype, self.c, self.h, self.w, self.scalling)

                # Send request
                start_time = time.time()
                if not self.async_set:
                    results.append(self.ctx.run(
                            { self.input_name : [image_data] },
                            {self.output_name: self.ctx.ResultFormat.RAW },
                            self.batch_size))
                    time_ = time.time() - start_time
                    print("inf time : ", time_)
cap = cv2.VideoCapture(0)
deepsort = TRTIS_deepsort(cap)
deepsort.start()
```

And I got this logs and error:
```
Failed to update context stat: [ 0] INTERNAL - Timer not set correctly.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "main_threads.py", line 184, in run
    self.batch_size))
  File "/usr/local/lib/python3.6/dist-packages/tensorrtserver/api/__init__.py", line 1582, in run
    self._last_request_id = _raise_if_error(c_void_p(_crequest_infer_ctx_run(self._ctx)))
  File "/usr/local/lib/python3.6/dist-packages/tensorrtserver/api/__init__.py", line 259, in _raise_if_error
    raise ex
tensorrtserver.api.InferenceServerException: [inference:0 49] unexpected shape for output 'features', model configuration shape is [1,128], inference shape is [1,128]
```

**Triton Information**
What version of Triton are you using?
I pulled 19.10-py3 server

from gitrepoitory I build client from this docker:

```
# Copyright (c) 2019-2020, NVIDIA CORPORATION. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#  * Neither the name of NVIDIA CORPORATION nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Default setting is building on nvidia/cuda:10.1-devel-ubuntu18.04
ARG BASE_IMAGE=nvidia/cuda:10.1-devel-ubuntu18.04

FROM ${BASE_IMAGE}

# Ensure apt-get won't prompt for selecting options
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
            software-properties-common \
            autoconf \
            automake \
            build-essential \
            cmake \
            curl \
            git \
            libopencv-dev \
            libopencv-core-dev \
            libssl-dev \
            libtool \
            pkg-config \
            python3 \
            python3-pip \
            python3-dev \
            rapidjson-dev && \
    pip3 install --upgrade wheel setuptools

RUN pip3 install opencv-python
RUN pip3 install --upgrade wheel grpcio-tools

# Build expects "python" executable (not python3).
RUN rm -f /usr/bin/python && \
    ln -s /usr/bin/python3 /usr/bin/python

# Build the client library and examples
WORKDIR /workspace
COPY VERSION .
COPY build build
COPY src/clients src/clients
COPY src/core src/core

RUN cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/workspace/install && \
    make -j16 trtis-clients
RUN cd install && \
    export VERSION=`cat /workspace/VERSION` && \
    tar zcf /workspace/v$VERSION.clients.tar.gz *

# For CI testing need to install a test script.
COPY qa/L0_client_tar/test.sh /tmp/test.sh

# Install an image needed by the quickstart and other documentation.
COPY qa/images/mug.jpg images/mug.jpg

# Install the dependencies needed to run the client examples. These
# are not needed for building but including them allows this image to
# be used to run the client examples.
RUN pip3 install --upgrade install/python/tensorrtserver-*.whl numpy pillow

ENV PATH //workspace/install/bin:${PATH}
ENV LD_LIBRARY_PATH /workspace/install/lib:${LD_LIBRARY_PATH}
```

**Expected behavior**
I want it works)

**Comment by bobtattvamasi** [comment]
Okay. I just deleted string "max_batch_size: 1" in my config file and problem gone away. But... I have another problem now:

```
run tf_deepsort_module
Failed to update context stat: [ 0] INTERNAL - Timer not set correctly.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "main_threads.py", line 184, in run
    self.batch_size))
  File "/usr/local/lib/python3.6/dist-packages/tensorrtserver/api/__init__.py", line 1582, in run
    self._last_request_id = _raise_if_error(c_void_p(_crequest_infer_ctx_run(self._ctx)))
  File "/usr/local/lib/python3.6/dist-packages/tensorrtserver/api/__init__.py", line 259, in _raise_if_error
    raise ex
tensorrtserver.api.InferenceServerException: [inference:0 43] 2 root error(s) found.
  (0) Invalid argument: Index out of range using input dim 2; input has only 2 dims
	 [[{{node map/while/strided_slice}}]]
	 [[features/_3]]
  (1) Invalid argument: Index out of range using input dim 2; input has only 2 dims
	 [[{{node map/while/strided_slice}}]]
0 successful operations.
0 derived errors ignored.
```
And I don't know what to do(

**Comment by bobtattvamasi** [comment]
so? The second error is because i deleted "max_batch_size: 1". so I return to first error...

**Comment by GuanLuo** [comment]
Can you try with a newer version of Triton? The error message has been improve and it should provide better guidance regarding the issue.

And do you know the shape expected by the model by any chance? The full shape which includes batch dimension if applicable

**Comment by bobtattvamasi** [comment]
Hello, Thanks for answer. But I found the solution. The first error is because I use batch_size. And it try to return [1, shape_of_output]. And it need  shape [1, 128]. But I already wrote in config [1,128]. That why it abuse on me. So I rewrite the shape of output from [1, 128] to [128] in my config file. And it works!
